name: "Deta create project"
on: [push]
 
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2 #Be sure you check-out the repo first. Deta CLI needs access to the files
      # Install Deta CLI as per docs
      # https://docs.deta.sh/docs/cli/install
      - name: Install Deta CLI
        shell: bash
        run: |
          curl -fsSL https://get.deta.dev/cli.sh | sh
      # Using the access token and existing Deta micro and project,
      # clone the micro and copy .deta metadata folder to use it in deploy
      # https://docs.deta.sh/docs/cli/commands#deta-clone
      - name: create a micro
        shell: bash
        run: |
          export DETA_ACCESS_TOKEN=${{ secrets.DETA_TOKEN }}
          ~/.deta/bin/deta new --node --name githubdetasone --project default tmp/
          cp -r tmp/.deta .
      # Using the access token, deploy the project to Deta
      # https://docs.deta.sh/docs/cli/commands#deta-deploy
      # - name: Deploy to Deta
      #   shell: bash
      #   run: |
      #     export DETA_ACCESS_TOKEN=${{ inputs.deta-access-token }}
      #     cd ${{ inputs.deta-project-dir }}
      #     ~/.deta/bin/deta deploy
